// ----------------------------------------------------------------------

export const link = ['/emerge-collection', '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',
 '/maintenance',  
];
