// ----------------------------------------------------------------------

export const productName = [
  'Nike Air Force',
  'Vans Old Skool',
  'Converse High Top',
  'Nike Jordan 1 Travis Scott',
  'Adidas Samba',
  'Nike Terminator High ',
  'Jordan 2 Retro',
  'Nike Air Penny 2 ',
  'Nike General Purpose Shoes',
  'New Balance 990v3 ',
  'Adidas Gazelle ',
  'Asics Gel-Nimbus 9 ',
  'Vans OG Style',
  'Louis Vuitton Monogram Air Force 1',
  'Nike Air Zoom',
  'Adidas Stan Smith',
  'Nike Air Griffey Max 1',
  'Adidas Orignials SL80',
  'New Balance M1300JP',
  'Converse Chuck Taylor High Top',
  'Nike Air Max 1 Jewel ',
  'Nike LeBron 7',
  'Nike Roshe',
  'Air Jordan 1 ',
  'Air Jordan 8',
  'Adidas Samba',
];
  